org.gradle.jvmargs=-Xmx3G

archives_base_name=BadOptimizations
mod_version=2.4.1

minecraft_version=26.3
neo_version=26.3.0.0-beta
java_version=25

fabric_loader_version=0.19.3
fabric_modmenu_version=20.0.0-beta.2

org.gradle.problems.report=false
org.gradle.caching=true

# 26.1+
fabric.loom.disableObfuscation=true